# Generated by Django 5.0.1 on 2024-02-13 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='channelID',
            new_name='channel_id',
        ),
        migrations.AddField(
            model_name='playlist',
            name='source',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='videomanager.playlistsource'),
            preserve_default=False,
        ),
    ]
