# Generated by Django 5.0.7 on 2024-08-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('QU', 'Queued'), ('DL', 'Downloaded'), ('ER', 'Error')], default='QU', max_length=10),
        ),
    ]
