# Generated by Django 5.0.7 on 2024-09-21 19:19

import videomanager.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanager', '0002_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', storage=videomanager.storage.ExistingFileStorage(), upload_to=''),
        ),
    ]
