# Generated by Django 5.0.2 on 2024-03-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanager', '0003_remove_video_file_path_video_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateField(),
        ),
    ]
