name: Test Workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Test Action
        uses: ./.github/actions/test
        with:
          python-version: 3.12.7
          YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}